#!/usr/bin/env ruby

require 'yaml'
CONFIG = YAML::load(File.open(File.join(File.dirname(__FILE__), 'config.yml')))

scripts_glob = File.join(File.dirname(__FILE__), "post-receive-*.rb")
Dir.glob scripts_glob do |filename|
  script = File.basename(filename, ".rb")
  puts "post-receive: #{script}"
  begin
    load filename
  rescue Exception => e
    puts "post-receive: #{script} FAILED: #{e}"
  end
end